name: dcs_app
description: Deep Cleaning Solutions App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  carousel_slider: ^4.2.1
  dio: ^5.4.3
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3              # ✅ नवीन — Guest ID UUID साठी
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env